export * from "./Home.jsx";
export * from "./Board.jsx";
export * from "./Calendar.jsx";
export * from "./Devs.jsx";
export * from "./Gallery.jsx";
export * from "./Join.jsx";
export * from "./Wecap.jsx";
export * from "./Board.jsx";
export * from "./Dashboard.jsx";
